[SOH] Move otrgen and make it more robust

diff --git a/ports/released/harbourmasters64/soh/soh/tools/otrgen b/ports/released/harbourmasters64/soh/soh/tools/otrgen
--- a/ports/released/harbourmasters64/soh/soh/tools/otrgen
+++ b/ports/released/harbourmasters64/soh/soh/tools/otrgen
@@ -1,13 +1,11 @@
 #!/bin/bash
 
-# Variables
+# Set up vars and logging
 GAMEDIR="$PWD"
-LOGFILE="$GAMEDIR/assets/otrlog.txt"
 BASEROMS_DIR="$GAMEDIR/baseroms"
 ARGS=""
 i=1
-
-exec > >(tee "$LOGFILE") 2>&1
+> "$GAMEDIR/patchlog.txt" && exec > >(tee "$GAMEDIR/patchlog.txt") 2>&1
 
 # Exports
 export LD_LIBRARY_PATH="$GAMEDIR/libs:$LD_LIBRARY_PATH"
@@ -60,9 +58,14 @@ process_roms() {
 }
 
 unzip_assets || { echo "Patching process failed!"; exit 1; }
-process_roms || { echo "Patching process failed!"; exit 1; }
+process_roms || { echo "Patching process failed!"; return 1; }
 
 # Run soh.elf with all ROM arguments
-eval "$GAMEDIR/soh.elf" $ARGS > "$GAMEDIR/otrlog.txt"
-
-echo "Patching process complete!"
+if eval "$GAMEDIR/soh.elf" "$ARGS" > "$GAMEDIR/tools/otrlog.txt"; then
+    echo "Patching process complete!"
+else
+    RET=$?
+    echo "Error: soh.elf crashed or returned error code $RET."
+    echo "Check $GAMEDIR/tools/otrlog.txt for specific extraction errors."
+    echo "Patching process failed!"
+fi
