[MADHOUSE] Add compatibility with early access title

diff --git a/ports/released/gamemakerengine/madhouse/madhouse/tools/patchscript b/ports/released/gamemakerengine/madhouse/madhouse/tools/patchscript
--- a/ports/released/gamemakerengine/madhouse/madhouse/tools/patchscript
+++ b/ports/released/gamemakerengine/madhouse/madhouse/tools/patchscript
@@ -29,8 +29,21 @@ else
     patch_failure
 fi
 
+# Mount the dotnet runtime
+DOTNETDIR="$HOME/mono"
+DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
+if [ -f "$DOTNETFILE" ]; then
+    $ESUDO mkdir -p "$DOTNETDIR"
+    $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
+    $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
+else
+    echo "This port requires the Dotnet runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
 # Exports
-export PATH="$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
+export PATH="$DOTNETDIR:$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
 export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
 export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
 export DATADIR="$GAMEDIR/assets"
@@ -65,43 +78,113 @@ if [ -z "$ZIP" ]; then
     patch_failure
 fi
 
-remove_files() {
+# Prepare game data
+# If there are audiogroups in the madhouse.port file, unzip them
+prepare_files() {
     # Delete unnecessary files
     rm -rf $DATADIR/*.exe $DATADIR/*.dll $DATADIR/.gitkeep
     echo "Removed unnecessary files"
+    
+    # Check if we're using a prepatched game
+    if unzip -l "$DATAFILE" "assets/*" | grep -q "assets/.*\.dat"; then
+        echo "Prepatched game detected."
+        PREPATCH=1
+        unzip_audiogroups || { patch_failure; return 1; }
+    fi
+}
+
+# Unzip audiogroups
+unzip_audiogroups() {
+    # Unzip from $DATAFILE into $DATADIR
+    echo "Unzipping ${DATAFILE}..."
+    mkdir -p assets
+    unzip -j -o "$DATAFILE" "assets/*.dat" -d "$DATADIR"
+    if [ $? -eq 0 ]; then
+        echo "Unzipped successfully to $DATADIR."
+    else
+        echo "Failed to unzip file."
+        return 1
+    fi
+}
+
+# Replace game code entries for data.win
+replace_code() {
+    # Build --code args from all gml files
+    CODEARGS=()
+    for file in "$GAMEDIR/tools/gml/"*.gml; do
+        [ -f "$file" ] || continue
+        entry=$(basename "$file" .gml)
+        echo "Adding modified gml script: $file"
+        CODEARGS+=(--code "$entry=$file")
+    done
+
+    # Replace scripts
+    if dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" replace "$DATADIR/data.win" -o "$DATADIR/data2.win" "${CODEARGS[@]}"; then
+        echo "Successfully replaced gml scripts."
+        mv -f "$DATADIR/data2.win" "$DATADIR/data.win"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
+    else
+        echo "Failed to replace gml scripts."
+        return 1
+    fi
+}
+
+# Compress audio files inside datafile and audiogroups
+compress_audio() {
+    # Purge cache before operations
+    rm -rf "$TMPDIR/"*
+    
+    # Test for data.win
     if [ -f "$DATADIR/data.win" ]; then
         mv "$DATADIR/data.win" "$DATADIR/game.droid"
     fi
-    sleep 1
-}
 
-compress_audio() {  
-    if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
-        mv "$TMPDIR/"* "$DATADIR" && rmdir "$TMPDIR"
+    # Run the compression tool
+    PYTHON=$(which python3)
+    if [ "$PREPATCH" != 1 ]; then
+        echo "Running GMTools on data and audiogroups."
+        $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"
+    else
+        echo "Running GMTools on data file only."
+        $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -O 0 -m 1000 -b 64 -r -d "$TMPDIR" "$DATADIR/game.droid"
+    fi
+
+    if [ $? -eq 0 ]; then
+        echo "Compression completed successfully."
+        mv "$TMPDIR/"* "$DATADIR"
+        echo "Moved compressed files to $DATADIR."
+        rm -rf "$TMPDIR"
+        echo "Temporary directory $TMPDIR removed."
         echo "Audio compression applied successfully."
     else
         # Failure
-        echo "Audio compression failed for $GAMEFILE."
+        echo "Audio compression failed
+        ."
         rmdir "$TMPDIR"
-        patch_failure
+        return 1
     fi
 }
 
+# Zip it all into the .port file
 zip_archive() {
-        echo "Finishing up..."
         zip -r -0 $DATAFILE ./assets/
         mkdir -p saves
         rm -rf $DATADIR/*
-        sleep 1
 }
 
+# Main function
 process_game() {
-    remove_files || { patch_failure; return 1; }
+    echo "Preparing game files..."
+    prepare_files
+    echo "Adding modified scripts..."
+    replace_code || { patch_failure; return 1; }
+    echo "Compressing audio..."
     compress_audio || { patch_failure; return 1; }
+    echo "Finishing up..."
     zip_archive || { patch_failure; return 1; }
 }
 
-# Call the function
+# Call main
 if ! process_game; then
     echo "Patching process failed!"
     mv "$LOGFILE" "$LOGERR"
