[SPAGHETTIKART] Update otrgen

diff --git a/ports/released/harbourmasters64/spaghettikart/spaghettikart/tools/otrgen b/ports/released/harbourmasters64/spaghettikart/spaghettikart/tools/otrgen
--- a/ports/released/harbourmasters64/spaghettikart/spaghettikart/tools/otrgen
+++ b/ports/released/harbourmasters64/spaghettikart/spaghettikart/tools/otrgen
@@ -34,9 +34,6 @@ unzip_assets() {
 # Function handle the ROM file.
 process_rom() {
     cd "$GAMEDIR/tools"
-    echo "[OTRGEN] Current directory is $PWD"
-    echo "[OTRGEN] Current files:"
-    ls
     local input_file="$1"
     if [ ! -f "../baseroms/$input_file" ]; then
         echo "[OTRGEN] Error: File $input_file not found!"
@@ -45,7 +42,7 @@ process_rom() {
 
     # Run the extraction
     echo "Extracting data from ../baseroms/$input_file..."
-    if do_torch "../baseroms/$input_file"; then
+    if ./torch o2r "../baseroms/$input_file" --additional-files meta/mods.toml >> "$LOGFILE"; then
         echo "[OTRGEN] Extraction complete. O2R generated."
         mv mk64.o2r ../mk64.o2r
     else
@@ -55,16 +52,12 @@ process_rom() {
     cd "$GAMEDIR"
 }
 
-do_torch() {
-    local rom_file="../baseroms/$1"
-    ./torch header -o "../baseroms/$1"
-    ./torch o2r "../baseroms/$1" --additional-files meta/mods.toml
-}
-
 # Function to convert N64 ROM to Z64 format
 convert_n64() {
     local rom_file="$1"
-    local output_file="baseroms/rom.z64"
+    local base_name
+    base_name=$(basename "$rom_file")
+    local output_file="baseroms/${base_name%.*}.z64"
 
     if [[ ! -f "$rom_file" ]]; then
         echo "Error: File $rom_file not found!"
@@ -94,6 +87,7 @@ convert_n64() {
     esac
 
     echo "[OTRGEN] Conversion complete. Saved as $output_file."
+    echo "$output_file"
 }
 
 # Main logic
@@ -120,9 +114,9 @@ echo "Processing $rom_file..."
 
 case "$rom_file" in
     *.n64)
-        convert_n64 "$rom_file" || { echo "Patching process failed!"; exit 1; }
+        converted_file=$(convert_n64 "$rom_file") || { echo "Patching process failed!"; exit 1; }
         rm -f "$rom_file"
-        process_rom "rom.z64"  || { echo "Patching process failed!"; exit 1; }
+        process_rom "$(basename "$converted_file")"  || { echo "Patching process failed!"; exit 1; }
         ;;
     *.z64)
         process_rom "$(basename "$rom_file")"  || { echo "Patching process failed!"; exit 1; }
