[SONICTT16B] Return to xdelta for texture compression

diff --git a/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript b/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript
--- a/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript
+++ b/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript
@@ -93,7 +93,7 @@ unzip_apk() {
 
             rm -rf "$TMPDIR" "$GAMEDIR/$APKFILE"
 
-            rm -f "$DATADIR"/*.exe "$DATADIR"/*.png "$DATADIR"/*.txt "$DATADIR"/.gitkeep
+            rm -f "$DATADIR"/*.exe "$DATADIR"/*.txt "$DATADIR"/.gitkeep "$DATADIR"/manual*.png "$DATADIR"/portrait_splash.png
 
         else
             echo "Error unzipping apk!"
@@ -102,6 +102,24 @@ unzip_apk() {
     else
         echo "Did not find $GAMEDIR/$APKFILE!"
         return 1
+    fi
+}
+
+apply_xdelta() {
+    # Check if the game.droid file exists and apply xdelta
+    if [ -f "$DATADIR/game.droid" ]; then
+        output=$($controlfolder/xdelta3 -d -s "$DATADIR/game.droid" -f "$GAMEDIR/tools/patches/sonictt16b.xdelta" "$DATADIR/game2.droid" 2>&1)
+        if [ $? -eq 0 ]; then
+            echo "Patch applied successfully"
+            echo "$output"
+            rm "$DATADIR/game.droid" && mv "$DATADIR/game2.droid" "$DATADIR/game.droid"
+        else
+            echo "Failed to apply patch"
+            echo "$output"
+            return 1
+        fi
+    else
+        echo "No game.droid file found to patch!"
     fi
 }
 
@@ -115,28 +133,6 @@ compress_audio() {
         echo "Audio compression failed."
         rmdir "$TMPDIR"
         return 1
-    fi
-}
-
-# Toggle GeneralInfo flags via envars - see https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModLib/Models/UndertaleGeneralInfo.cs for options
-set_flags() {
-    export SET_FLAGS="Fullscreen"
-    export CLEAR_FLAGS="Scale"
-    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
-        load "$DATADIR/game.droid" \
-        -s "$GAMEDIR/tools/toggleflags.csx" \
-        -o "$DATADIR/game2.droid"
-
-    if [ $? -ne 0 ]; then
-        echo "Failed to toggle info flags."
-        return 1
-    else
-        echo "Successfully toggled info flags."
-        rm -f "$DATADIR/game.droid"
-        mv "$DATADIR/game2.droid" "$DATADIR/game.droid"
-        if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]; then
-            rm -rf "$TMPDIR"/*
-        fi
     fi
 }
 
@@ -160,10 +156,10 @@ process_game() {
     prepare_system || { cleanup; return 1; }
     echo "Looking for apk file..."
     unzip_apk || { cleanup; return 1; }
+    echo "Applying patch..."
+    apply_xdelta || { cleanup; return 1; }
     echo "Compressing audio..."
     compress_audio || { cleanup; return 1; }
-    echo "Toggling GeneralInfo flags..."
-    set_flags || { cleanup; return 1; }
     echo "Finishing up..."
     zip_archive || { cleanup; return 1; }
 }
